#!/bin/bash
#
################################################################################
#
#       Filename: reflector
#
#       Author: Daniel Huckson
#       Version 1.0
#   Date: 2014/06/28
#       Purpose: Mirror source site A to destination site B.
#
################################################################################
#
[[ -f $1 ]] && {
	retval=0
	source $1

	[ -f ~/.ssh/id_rsa.pub ] || {
		clear
		echo -e "\n\n"
		echo -e "*******************************************************************"
		echo -e "\n  *** NOTICE *** Creating private and public, "
		echo -e " encryption keys. Please enter required information to continue.\n"
		echo -e "*******************************************************************"

		echo -e "\n\n\n" | ssh-keygen -t rsa -N ""  > /dev/null 2>&1

		ssh-copy-id -i ~/.ssh/id_rsa.pub $src_usr@$src_url

		echo -e "\n"
		echo -e "*******************************************************************\n\n\n"
	}

	start_time=$(date +%s)

	[ -f $tmp_file ] && rm -f $tmp_file

	echo "Mirroring of $src_domain to $dst_domain."  | tee -a $tmp_file
	echo "----------------------------------------------------------------------"  | tee -a $tmp_file

	for index in ${!src_que[*]}; do
		rsync -avzh --delete $src_usr@$src_url:${src_que[$index]} ${dst_que[$index]} 2>&1 | tee -a $tmp_file
	done

	cd $script_src/injector && ./injector -f configs/injector.cfg

	[[ $? -ne 0 ]] && {
		retval=1
		echo -e "\nMirroring of $src_domain to $dst_domain did not complete successfully." | tee -a $tmp_file
	}

	s=$[$(date +%s) - $start_time]; h=$[$s / 3600]; s=$[$s - $[$h * 3600]]; m=$[$s / 60]; s=$[$s - $[m * 60]]
	[ "$h" != '0' ] && hours=" $h hours" || hours=""
	[ "$m" != '0' ] && minutes=" $m minutes and" || minutes=""

	echo -e "\nTotal mirroring time$hours$minutes $s seconds.\n\n" | tee -a $tmp_file

	[[ $results -eq 0 ]] && state="Successful" || state="Failed"
	(cat $tmp_file) | mailx -r "$email_from ($email_from_nice_name)" -s "'Mirroring of $src_domain to $dst_domain ($state!)' `date`" "$email_recipients"
	[ -f "$tmp_file" ] && rm -f $tmp_file
} || {
        echo -e "\nCan't find the configutation file $1!\n"
}


